version: '3'

services:
  db:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_DATABASE: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker
    ports:
       - "3306:3306"

      
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - rabbitmq
  rabbitmq:
    container_name: "rabbitmq1"
    tty: true
    image: rabbitmq:3.7-rc
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672" 
